---
    platform            : irc
    ircServer           : irc.pine64.org # IRC server to connect to
    ircPort             : 6667 # IRC port (TLS is not yet supported)
    ircNick             : NoMoreSpam # IRC nick
    channels            : "#spammychannel #anotherspammychannel" # Channels to monitor
    spamModel           : compiled_model.json # file name for your spam model
    alertThreshold      : 0.5 # Minimum spam confidence value to trigger alert
    logThresholdHigh    : 0.8 # High spam confidence value to trigger save to spam file
    logThresholdLow     : 0.6 # Low spam/good confidence value to trigger save to spam file
    spamFile            : "spamLog.json" # filename to save messages that meet log threshold
    classifyBypass      : true # true to enable the known user classification bypass
    messageThreshold    : 5 # number of previous messages a user must have sent before qualifying for classify bypass
    persistKnownUsers   : True, # set to true to enable persistence of known user data across bot restarts
    persistFile         : knownUsers.json # file name for known user persistence
    notificationChannel : "*" # name of the channel you want to receive spam notifications in. Set to a nick to receive notifications via private message, or to "*" to receive notifications in the same channel as the spam.
    spamNotifyPing      : yournick   # put a nick here to ping it for spam notifications. Leave blank for no ping.
    spamNotifyMessage   : Potential spam detected. # message to use in spam notifications
    bridgeBot           : bridgebot # if your channel(s) use(s) a bridgebot (like matterbridge) to connect other networks, put its nick here (set to an invalid nick value such as "*" if you don't have a bridgebot)
    debugMode           : false # output additional data in console and notification messages. Unless you know otherwise, you should probably have this set to false.
