---
    platform            : discord
    discordToken        : ABCDEF1234567890 # Make sure to put your bot token here before starting!
    spamModel           : compiled_model.json # file name for your spam model
    spamFile            : "spamLog.json" # filename to save messages that meet log threshold
    persistKnownUsers   : True, # set to true to enable persistence of known user data across bot restarts
    persistFile         : knownUsers.json # file name for known user persistence
    notificationChannel : spam-tracker # name of the channel you want to receive spam notifications in. If this channel is not accessible, notifications will occur in the same channel as spam.
    spamNotifyPing      : Moderator   # put a role name here to ping it for spam notifications. Leave blank for no ping.
    spamNotifyMessage   : Potential spam detected. # message to use in spam notifications
    bridgeBot           : Pine64 Protocol Droid#9618 # if your server uses a bridgebot (like matterbridge) to connect other networks, put its discord name + discriminator here
    debugMode           : false # output additional data in console and notification messages. Unless you know otherwise, you should probably have this set to false.
    ocrEnable           : false # enable scanning of images (requires additional python modules, see README)
    autoDeleteAPI       : none # only currently available options are "customMB" (for gamiee's modified Matterbridge) or "none" (disabled)
    bridgeURL           : "127.0.0.1:1223" # only necessary if using an autodelete method that requires HTTP API calls (customMB)
    publicDeleteNotice  : "Automated message: a message was detected by CedarSentinel as spam and was automatically deleted. If this was in error, please contact a moderator." # message to use in spam auto-delete public notifications
